### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jimparis** [XenGi/microftx#7]
Hi,
This project includes the _CC-BY 3.0 Unported_ license, but is derived from the original MicroFTX design, which was licensed under the _CC-BY-SA 3.0 Unported_ license.  CC-BY-SA requires that derivatives follow the same license, so I'd like to request that you please correct the license file in this repository.  Let me know if you'd like me to provide a pull request.
Thanks,
Jim

**Comment by XenGi** [comment]
Should be fixed with 42c6ab4. Thx for the sharp eye. ;)
